version: '2'
services:
  app:
    build: .
    image: rebbot
    volumes:
      - "${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}"
    ports:
      - "8080:8080"
    environment:
      - SSH_AUTH_SOCK
      - DATASTORE_EMULATOR_HOST=googlesdk:8081
    depends_on:
      - googlesdk

  googlesdk:
    # TODO: Upgrade to Cassandra 3.0. See also [1].
    # [1] https://tink.slack.com/archives/C7GR0LQ8M/p1541064997040200
    image: singularities/datastore-emulator
#    ports:
#      - "8081:8081"
    environment:
      - DATASTORE_PROJECT_ID=project-test
      - DATASTORE_LISTEN_ADDRESS=0.0.0.0:8081
